// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsadapter} from '../models';
import {model} from '../models';
import {holdings} from '../models';
import {context} from '../models';
import {port} from '../models';

export function EmitFlowNow():Promise<void>;

export function EnsureSelfContainer(arg1:string,arg2:string):Promise<void>;

export function ExportAll(arg1:string):Promise<Array<wailsadapter.ExportResult>>;

export function ExportDataset(arg1:string,arg2:string):Promise<wailsadapter.ExportResult>;

export function ExternalRefreshSignal():Promise<any>;

export function FlowBreakdown(arg1:string):Promise<Array<model.FlowItemStatView>>;

export function FlowSummary():Promise<model.SessionSummary>;

export function HoldingsSummary():Promise<model.HoldingsSummary>;

export function IngestBankVault(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function IngestCityVaultValues(arg1:Record<string, number>):Promise<void>;

export function IngestContainer(arg1:string,arg2:string,arg3:Array<holdings.SlotItem>):Promise<void>;

export function IngestDeleteItem(arg1:number):Promise<void>;

export function IngestEMV(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function IngestEquipment(arg1:Array<holdings.ItemRef>):Promise<void>;

export function IngestFame(arg1:string,arg2:number,arg3:number):Promise<void>;

export function IngestGather(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string):Promise<void>;

export function IngestLoot(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string):Promise<void>;

export function IngestMarket(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function IngestMarketPrice(arg1:string,arg2:number,arg3:number):Promise<void>;

export function IngestPutItem(arg1:string,arg2:number,arg3:holdings.ItemRef):Promise<boolean>;

export function IngestSelfContainer(arg1:string,arg2:string,arg3:Array<holdings.SlotItem>):Promise<void>;

export function IngestSilver(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function IngestVaultSummaryTab(arg1:string,arg2:string,arg3:string,arg4:Array<holdings.ItemRef>):Promise<void>;

export function ListFlow():Promise<Array<model.FlowEventView>>;

export function ListHoldings():Promise<Array<model.HoldingItem>>;

export function ListItems():Promise<Array<model.LiveViewItem>>;

export function RefreshExternalPrices(arg1:context.Context,arg2:port.PriceFetcher):Promise<number>;

export function SetCurrentCity(arg1:string):Promise<void>;

export function SetFlowReader(arg1:wailsadapter.FlowReader,arg2:string):Promise<void>;

export function SetSelf(arg1:number,arg2:string):Promise<void>;

export function SetSpec(arg1:model.CharacterSpec):Promise<void>;

export function SetSpecEnum(arg1:Array<number>):Promise<void>;

export function SetSpecUnlocked(arg1:Array<number>):Promise<void>;

export function SetStatus(arg1:model.CaptureStatusView):Promise<void>;

export function SetUIContext(arg1:context.Context):Promise<void>;

export function SetWallet(arg1:number,arg2:number):Promise<void>;

export function SetZone(arg1:string):Promise<void>;

export function Spec():Promise<model.CharacterSpec>;

export function SpecEnumSnapshot():Promise<Array<number>>;

export function SpecUnlockedSnapshot():Promise<Array<number>>;

export function StartFlowPersistence(arg1:context.Context,arg2:wailsadapter.FlowStore,arg3:string):Promise<void>;

export function Status():Promise<model.CaptureStatusView>;

export function StopFlowPersistence():Promise<void>;

export function ZoneStats(arg1:string):Promise<Array<model.ZoneStatView>>;
