// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {holdings} from '../models';

export function HoldingsSummary():Promise<model.HoldingsSummary>;

export function IngestBankVault(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function IngestContainer(arg1:string,arg2:string,arg3:Array<holdings.SlotItem>):Promise<void>;

export function IngestDeleteItem(arg1:number):Promise<void>;

export function IngestEMV(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function IngestEquipment(arg1:Array<holdings.ItemRef>):Promise<void>;

export function IngestMarket(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function IngestPutItem(arg1:string,arg2:number,arg3:holdings.ItemRef):Promise<void>;

export function IngestSelfContainer(arg1:string,arg2:string,arg3:Array<holdings.SlotItem>):Promise<void>;

export function ListHoldings():Promise<Array<model.HoldingItem>>;

export function ListItems():Promise<Array<model.LiveViewItem>>;

export function SetCurrentCity(arg1:string):Promise<void>;

export function SetSpec(arg1:Array<number>):Promise<void>;

export function SetStatus(arg1:model.CaptureStatusView):Promise<void>;

export function Spec():Promise<model.CharacterSpec>;

export function Status():Promise<model.CaptureStatusView>;
