// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function IngestEMV(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function IngestMarket(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ListItems():Promise<Array<model.LiveViewItem>>;

export function SetStatus(arg1:model.CaptureStatusView):Promise<void>;

export function Status():Promise<model.CaptureStatusView>;
