// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitFlowNow() {
  return window['go']['wailsadapter']['Service']['EmitFlowNow']();
}

export function EnsureSelfContainer(arg1, arg2) {
  return window['go']['wailsadapter']['Service']['EnsureSelfContainer'](arg1, arg2);
}

export function FlowBreakdown(arg1) {
  return window['go']['wailsadapter']['Service']['FlowBreakdown'](arg1);
}

export function FlowSummary() {
  return window['go']['wailsadapter']['Service']['FlowSummary']();
}

export function HoldingsSummary() {
  return window['go']['wailsadapter']['Service']['HoldingsSummary']();
}

export function IngestBankVault(arg1, arg2) {
  return window['go']['wailsadapter']['Service']['IngestBankVault'](arg1, arg2);
}

export function IngestCityVaultValues(arg1) {
  return window['go']['wailsadapter']['Service']['IngestCityVaultValues'](arg1);
}

export function IngestContainer(arg1, arg2, arg3) {
  return window['go']['wailsadapter']['Service']['IngestContainer'](arg1, arg2, arg3);
}

export function IngestDeleteItem(arg1) {
  return window['go']['wailsadapter']['Service']['IngestDeleteItem'](arg1);
}

export function IngestEMV(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestEMV'](arg1, arg2, arg3, arg4);
}

export function IngestEquipment(arg1) {
  return window['go']['wailsadapter']['Service']['IngestEquipment'](arg1);
}

export function IngestFame(arg1, arg2, arg3) {
  return window['go']['wailsadapter']['Service']['IngestFame'](arg1, arg2, arg3);
}

export function IngestGather(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsadapter']['Service']['IngestGather'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function IngestLoot(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wailsadapter']['Service']['IngestLoot'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function IngestMarket(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestMarket'](arg1, arg2, arg3, arg4);
}

export function IngestMarketPrice(arg1, arg2, arg3) {
  return window['go']['wailsadapter']['Service']['IngestMarketPrice'](arg1, arg2, arg3);
}

export function IngestPutItem(arg1, arg2, arg3) {
  return window['go']['wailsadapter']['Service']['IngestPutItem'](arg1, arg2, arg3);
}

export function IngestSelfContainer(arg1, arg2, arg3) {
  return window['go']['wailsadapter']['Service']['IngestSelfContainer'](arg1, arg2, arg3);
}

export function IngestSilver(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestSilver'](arg1, arg2, arg3, arg4);
}

export function IngestVaultSummaryTab(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestVaultSummaryTab'](arg1, arg2, arg3, arg4);
}

export function ListFlow() {
  return window['go']['wailsadapter']['Service']['ListFlow']();
}

export function ListHoldings() {
  return window['go']['wailsadapter']['Service']['ListHoldings']();
}

export function ListItems() {
  return window['go']['wailsadapter']['Service']['ListItems']();
}

export function SetCurrentCity(arg1) {
  return window['go']['wailsadapter']['Service']['SetCurrentCity'](arg1);
}

export function SetFlowReader(arg1, arg2) {
  return window['go']['wailsadapter']['Service']['SetFlowReader'](arg1, arg2);
}

export function SetSelf(arg1, arg2) {
  return window['go']['wailsadapter']['Service']['SetSelf'](arg1, arg2);
}

export function SetSpec(arg1) {
  return window['go']['wailsadapter']['Service']['SetSpec'](arg1);
}

export function SetStatus(arg1) {
  return window['go']['wailsadapter']['Service']['SetStatus'](arg1);
}

export function SetZone(arg1) {
  return window['go']['wailsadapter']['Service']['SetZone'](arg1);
}

export function Spec() {
  return window['go']['wailsadapter']['Service']['Spec']();
}

export function StartFlowPersistence(arg1, arg2, arg3) {
  return window['go']['wailsadapter']['Service']['StartFlowPersistence'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['wailsadapter']['Service']['Status']();
}

export function StopFlowPersistence() {
  return window['go']['wailsadapter']['Service']['StopFlowPersistence']();
}

export function ZoneStats(arg1) {
  return window['go']['wailsadapter']['Service']['ZoneStats'](arg1);
}
