// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IngestEMV(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestEMV'](arg1, arg2, arg3, arg4);
}

export function IngestMarket(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestMarket'](arg1, arg2, arg3, arg4);
}

export function ListItems() {
  return window['go']['wailsadapter']['Service']['ListItems']();
}

export function SetStatus(arg1) {
  return window['go']['wailsadapter']['Service']['SetStatus'](arg1);
}

export function Status() {
  return window['go']['wailsadapter']['Service']['Status']();
}
