// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HoldingsSummary() {
  return window['go']['wailsadapter']['Service']['HoldingsSummary']();
}

export function IngestBankVault(arg1, arg2) {
  return window['go']['wailsadapter']['Service']['IngestBankVault'](arg1, arg2);
}

export function IngestContainer(arg1, arg2, arg3) {
  return window['go']['wailsadapter']['Service']['IngestContainer'](arg1, arg2, arg3);
}

export function IngestEMV(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestEMV'](arg1, arg2, arg3, arg4);
}

export function IngestEquipment(arg1) {
  return window['go']['wailsadapter']['Service']['IngestEquipment'](arg1);
}

export function IngestMarket(arg1, arg2, arg3, arg4) {
  return window['go']['wailsadapter']['Service']['IngestMarket'](arg1, arg2, arg3, arg4);
}

export function ListHoldings() {
  return window['go']['wailsadapter']['Service']['ListHoldings']();
}

export function ListItems() {
  return window['go']['wailsadapter']['Service']['ListItems']();
}

export function SetCurrentCity(arg1) {
  return window['go']['wailsadapter']['Service']['SetCurrentCity'](arg1);
}

export function SetSpec(arg1) {
  return window['go']['wailsadapter']['Service']['SetSpec'](arg1);
}

export function SetStatus(arg1) {
  return window['go']['wailsadapter']['Service']['SetStatus'](arg1);
}

export function Spec() {
  return window['go']['wailsadapter']['Service']['Spec']();
}

export function Status() {
  return window['go']['wailsadapter']['Service']['Status']();
}
